apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.targetPort }}
        env:
          - name: spring.profiles.active
            value: {{ .Values.app.profile }}
          - name: DB_URL
            value: {{ .Values.app.dbUrl }}
          - name: DB_USERNAME
            value: {{ .Values.db.username }}
          - name: DB_PASSWORD
            value: {{ .Values.db.password }}
          - name: KAFKA_BROKER
            value: {{ .Values.kafka.name }}:{{ .Values.kafka.port }}

