apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: {{ .Values.db.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.db.port }}
      protocol: TCP
  selector:
    app: {{ .Values.db.name }}
