apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kafka.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name }}
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "{{ .Values.kafka.name }}"
      containers:
        - name: {{ .Values.kafka.name }}
          image: wurstmeister/kafka
          ports:
            - containerPort: {{ .Values.kafka.port }}
          env:
            - name: ENABLE_AUTO_EXTEND
              value: "true"
            - name: KAFKA_RESERVED_BROKER_MAX_ID
              value: "999999999"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_PORT
              value: "{{ .Values.kafka.port }}"
            - name: KAFKA_ADVERTISED_PORT
              value: "{{ .Values.kafka.port }}"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "{{ .Values.kafka.name }}"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ .Values.zookeeper.name }}:{{ .Values.zookeeper.port }}"
