apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.name }}
  labels:
    app: {{ .Values.zookeeper.name }}
spec:
  ports:
  - name: client
    port: {{ .Values.zookeeper.port }}
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: {{ .Values.zookeeper.name }}
