apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.zookeeper.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.zookeeper.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.zookeeper.name }}
    spec:
      containers:
      - name: {{ .Values.zookeeper.name }}
        image: digitalwonderland/zookeeper
        ports:
          - containerPort: {{ .Values.zookeeper.port }}
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: {{ .Values.zookeeper.name }}

