
replicaCount: 1

image:
  repository: localhost:5000/com.jmgits/transaction-report
  tag: 1.0.0-SNAPSHOT
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

app:
  name: app
  port: 8080
  profile: dev
  dbUrl: jdbc:postgresql://postgres/transaction-report-db

db:
  name: postgres
  port: 5432
  database: transaction-report-db
  username: transaction-report-user
  password: transaction-report-password

kafka:
  name: kafka
  port: 9092

zookeeper:
  name: zookeeper
  port: 2181

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
